- hosts: all
  vars:
    pkgstoinstall: [ libffi-dev, libssl-dev, python3, python3-pip ]
  pre_tasks:
    - name: Install a list of packages
      become: yes
      apt:
        name: "{{ pkgstoinstall }}"
        update_cache: yes
        cache_valid_time: 86400

    - name: Remove python-configparser package
      become: yes
      apt:
        name: python-configparser
        state: absent

  roles:
    - role: docker
      become: yes
