- name: Create the app folder
  file:
    path: /home/{{ ansible_user }}/systranca
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    state: directory
    mode: '0755'

- name: Setup mosquitto config file
  become: yes
  copy:
    src: ../files/mosquitto.conf
    dest: /home/{{ ansible_user }}/systranca/mosquitto.conf
    # This is the mosquitto user if you don't set to this the container will
    # change it for you and your playbook will fail every second time
    owner: 1883
    group: 1883
    mode: '0644'

- name: Setup docker-compose.yml
  copy:
    src: ../files/docker-compose.yml
    dest: /home/{{ ansible_user }}/systranca/docker-compose.yml
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0644'

- name: Start containers
  community.docker.docker_compose:
    project_src: /home/{{ ansible_user }}/systranca
