- name: get docker convenience script
  shell: curl -fsSL https://get.docker.com -o get-docker.sh
  args:
    creates: /home/pi/get-docker.sh

- name: install docker
  shell: sh /home/pi/get-docker.sh
  args:
    creates: /usr/bin/docker

- name: make pi user execute docker commands
  user:
    name: pi
    groups:
      - docker
      - adm
      - dialout
      - cdrom
      - sudo
      - audio
      - video
      - plugdev
      - games
      - users
      - input
      - netdev
      - gpio
      - i2c
      - spi
    append: yes

- name: install docker-compose
  shell: pip3 -v install docker-compose
  args:
    creates: /usr/local/bin/docker-compose
